name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint
      if: always()

    - name: Run tests
      run: npm test
      if: always()

    - name: Build extension
      run: npm run build
      if: always()

    - name: Run web-ext lint
      run: npm run web-ext-lint
      if: always()

    - name: Run security audit
      run: npm audit --omit=dev
      if: always()

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-build
        path: web-ext-artifacts/
        if-no-files-found: error

  web-ext-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci

    - name: Lint with web-ext
      run: npm run web-ext-lint
      if: always() 